# VitalMc Core configuration

# Core License
license: ""

# Storage Section
storage:
  # Databases (You can create how much databases you need)
  databases:
    # Database Identifier
    main_storage:
      # Database Host
      host: "localhost:3306"
      # Database name
      database: ""
      # Database user
      user: ""
      # Database password
      password: ""
    # Database Identifier
    prison_storage:
      # Database Host
      host: "localhost:3306"
      # Database name
      database: ""
      # Database user
      user: ""
      # Database password

# Economy formats
formats:
  - ""
  - "K"
  - "M"
  - "B"
  - "T"
  - "Q"
  - "QQ"